// This file is generated by pnpm icons:generate. Do not edit.

import {createSVG} from '../TEMPLATE'

export const ArrowDownWideNarrow = createSVG({
  elements: [
    {
      fill: 'none',
      stroke: 'currentColor',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
      strokeWidth: 2,
      type: 'path',
      d: 'm3 16 4 4 4-4M7 20V4M11 4h10M11 8h7M11 12h4',
    },
  ],
  viewBox: '0 0 24 24',
})
