// This file is generated by pnpm icons:generate. Do not edit.

import {createSVG} from '../TEMPLATE'

export const CircleX = createSVG({
  elements: [
    {
      fill: 'none',
      stroke: 'currentColor',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
      strokeWidth: 2,
      type: 'circle',
      cx: 12,
      cy: 12,
      r: 10,
    },
    {
      fill: 'none',
      stroke: 'currentColor',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
      strokeWidth: 2,
      type: 'path',
      d: 'm15 9-6 6M9 9l6 6',
    },
  ],
  viewBox: '0 0 24 24',
})
