name: Nightly Update Translations
on:
  schedule:
    - cron: "0 2 * * *" # 2 AM UTC
  workflow_dispatch:

jobs:
  build-translations:
    name: Build Translations
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Install node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        uses: Wandalen/wretry.action@e68c23e6309f2871ca8ae4763e7629b9c258e1ea # v3.8.0
        with:
          command: pnpm install --frozen-lockfile
          attempt_limit: 3
          attempt_delay: 2000

      - name: Build translations
        run: pnpm intl:build

      - name: Commit updated translations
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "chore: nightly translation build"
          file_pattern: src/locale/locales/**/*.js